<?php

namespace ContainerXPDZgNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LB3QbEqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lB3QbEq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lB3QbEq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typologieService' => ['privates', 'App\\Service\\TypologieService', 'getTypologieServiceService', true],
        ], [
            'typologieService' => 'App\\Service\\TypologieService',
        ]);
    }
}
