<?php

namespace ContainerXPDZgNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JAzeLl7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jAzeLl7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jAzeLl7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ResService' => ['privates', 'App\\Service\\ReservationService', 'getReservationServiceService', true],
        ], [
            'ResService' => 'App\\Service\\ReservationService',
        ]);
    }
}
