<?php

namespace ContainerXPDZgNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Za4IzopService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.za4Izop' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.za4Izop'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'avaiService' => ['privates', 'App\\Service\\AvailibilityService', 'getAvailibilityServiceService', true],
        ], [
            'avaiService' => 'App\\Service\\AvailibilityService',
        ]);
    }
}
