<?php

namespace ContainerXPDZgNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDispoServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\DispoService' shared autowired service.
     *
     * @return \App\Service\DispoService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DispoService.php';

        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['App\\Service\\DispoService'])) {
            return $container->privates['App\\Service\\DispoService'];
        }

        return $container->privates['App\\Service\\DispoService'] = new \App\Service\DispoService(($container->privates['App\\Repository\\DisponibiliteRepository'] ?? $container->load('getDisponibiliteRepositoryService')), ($container->privates['App\\Repository\\TypologieRepository'] ?? $container->load('getTypologieRepositoryService')), $a);
    }
}
