<?php

namespace ContainerXPDZgNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExampleEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Email\ExampleEmail' shared autowired service.
     *
     * @return \App\Email\ExampleEmail
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'ExampleEmail.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Email\\ExampleEmail'])) {
            return $container->privates['App\\Email\\ExampleEmail'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['App\\Email\\ExampleEmail'])) {
            return $container->privates['App\\Email\\ExampleEmail'];
        }
        $c = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['App\\Email\\ExampleEmail'])) {
            return $container->privates['App\\Email\\ExampleEmail'];
        }

        return $container->privates['App\\Email\\ExampleEmail'] = new \App\Email\ExampleEmail(new \Symfony\Component\Mailer\Mailer($a, $b, $c));
    }
}
