<?php

namespace ContainerXPDZgNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrixServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PrixService' shared autowired service.
     *
     * @return \App\Service\PrixService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PrixService.php';

        $a = ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'));

        if (isset($container->privates['App\\Service\\PrixService'])) {
            return $container->privates['App\\Service\\PrixService'];
        }

        return $container->privates['App\\Service\\PrixService'] = new \App\Service\PrixService(($container->privates['App\\Repository\\PrixRepository'] ?? $container->load('getPrixRepositoryService')), ($container->privates['App\\Repository\\TypologieRepository'] ?? $container->load('getTypologieRepositoryService')), $a);
    }
}
