<?php

namespace ContainerXPDZgNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypologieServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TypologieService' shared autowired service.
     *
     * @return \App\Service\TypologieService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TypologieService.php';

        return $container->privates['App\\Service\\TypologieService'] = new \App\Service\TypologieService(($container->privates['App\\Repository\\TypologieRepository'] ?? $container->load('getTypologieRepositoryService')));
    }
}
