<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXPDZgNx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXPDZgNx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXPDZgNx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXPDZgNx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXPDZgNx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XPDZgNx',
    'container.build_id' => '9a2f1431',
    'container.build_time' => 1685028177,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXPDZgNx');
