<?php

namespace ContainerDnbPUZz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IDb3kBmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iDb3kBm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iDb3kBm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exampleEmail' => ['privates', 'App\\Email\\ExampleEmail', 'getExampleEmailService', true],
        ], [
            'exampleEmail' => 'App\\Email\\ExampleEmail',
        ]);
    }
}
