<?php

namespace ContainerDnbPUZz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtablissementServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EtablissementService' shared autowired service.
     *
     * @return \App\Service\EtablissementService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EtablissementService.php';

        return $container->privates['App\\Service\\EtablissementService'] = new \App\Service\EtablissementService(($container->privates['App\\Repository\\EtablissementRepository'] ?? $container->load('getEtablissementRepositoryService')));
    }
}
