<?php

namespace ContainerDnbPUZz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMealPlanServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MealPlanService' shared autowired service.
     *
     * @return \App\Service\MealPlanService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MealPlanService.php';

        return $container->privates['App\\Service\\MealPlanService'] = new \App\Service\MealPlanService(($container->privates['App\\Repository\\MealPlanRepository'] ?? $container->load('getMealPlanRepositoryService')));
    }
}
